### ISSUE TITLE
inverter (kWh) displays value 0

### ISSUE THREAD

**Issue by foakss** [sincze/Domoticz-Growatt-Webserver-Plugin#39]
The inverter (kWh) tile displays today's value as 0. The device inverter (kWh) in the device list displays the correct value.
Domoticz version 2023.1 on Raspberry PI 3B

**Comment by ariankoster** [comment]
Same problem, with same Domoticz version 2023.1 on Raspberry PI 3B

**Comment by sincze** [comment]
Is this all of a sudden ? Or did it work correctly before?
Can you share a screenshot to better understand the issue?

**Comment by ariankoster** [comment]
Since I installed it, it never worked OK for an intire day. my app gives also an error, but not when I turn off the domoticz plugin. I will turn it on and share screenshot later Met vriendelijke groetArian Koster Op 9 jul. 2023 om 17:01 heeft Sandor ***@***.***> het volgende geschreven:﻿
Is this all of a sudden ? Or did it work correctly before?
Can you share a screenshot to better understand the issue?

**Comment by sincze** [comment]
Mmm interesting, for my monitoring system I have
https://github.com/sincze/Domoticz/blob/master/growatt-inverter.php
and myself not using the plugin anymore.

**Comment by ariankoster** [comment]
thx for the tip. I have got it running Met vriendelijke groetArian Koster Op 9 jul. 2023 om 18:20 heeft Sandor ***@***.***> het volgende geschreven:﻿
Mmm interesting, for my monitoring system I have
https://github.com/sincze/Domoticz/blob/master/growatt-inverter.php
and myself not using the plugin anymore.
